---
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe Problem
      description: What problem did you have?
      placeholder: Something is broken.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: 1.0.0
    validations:
      required: true
