---
blank_issues_enabled: true
contact_links:
  - name: Python Information
    url: https://www.python.org/
    about: Python Org Website
  - name: Django Information
    url: https://docs.djangoproject.com/
    about: Django Website
