# Generated by Django 5.2.7 on 2025-10-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="portfolio_img",
            field=models.ImageField(blank=True, null=True, upload_to="portfolio_blog/about/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_img",
            field=models.ImageField(blank=True, null=True, upload_to="portfolio_blog/projects/"),
        ),
        migrations.AlterField(
            model_name="resumecertifications",
            name="credential_img",
            field=models.ImageField(blank=True, null=True, upload_to="portfolio_blog/certifications/"),
        ),
        migrations.AlterField(
            model_name="resumeskills",
            name="skill_img",
            field=models.ImageField(blank=True, null=True, upload_to="portfolio_blog/skills/"),
        ),
    ]
